#!/usr/bin/env python
import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    x = bin(n)[2:]

    a = 0
    b = 0
    for i in x:
        if i == '1':
            a += 1
            if a >= b:
                b = a
        if i == '0':
            a = 0
    print(b)
