#!/usr/bin/env python
import math
import os
import random
import re
import sys



if __name__ == '__main__':
    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = -9 * 9

    for i in range(6):
        for j in range(6):
            if i + 2 < 6 and j + 2 < 6:
                current_sum = arr[i][j] + arr[i][j+1] + arr[i][j+2] + arr[i+1][j+1]\
                              + arr[i+2][j] + arr[i+2][j+1] + arr[i+2][j+2]
            if current_sum > result:
                result = current_sum
    print(result)
