#!/usr/bin/env python
phoneBook = {}
x = int(input())

for n in range(x):
    name, num = input().strip().split(' ')
    name, num = [str(name), int(num)]
    phoneBook[name] = num

while True:
    try:  
        command = input()

        if command in phoneBook:
            output = ''.join('%s=%r' % (command, phoneBook[command]))
            print(output)
        else:
            print("Not found")
    except EOFError:
        break
